apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snyk-broker.fullname" . }}-broker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "snyk-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "snyk-broker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "snyk-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-broker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.scmType}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.container.containerPort }}
          env:
          {{- if eq .Values.scmType "github-com" }}
       # Github
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: GITHUB_TOKEN
              value: {{ .Values.scmToken }}
            - name: PORT
              value: {{ .Values.deployment.container.containerPort | squote }}
            - name: BROKER_CLIENT_URL
              value: {{ .Values.brokerClientUrl }}
          {{- end }}
          {{- if eq .Values.scmType "github-enterprise" }}
        # Github Enterprise
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: GITHUB_TOKEN
              value: {{ .Values.scmToken }}
            - name: GITHUB
              value: {{ .Values.github }}
            - name: GITHUB_API
              value: {{ .Values.githubApi }}
            - name: GITHUB_GRAPHQL
              value: {{ .Values.githubGraphQl}}              
            - name: PORT
              value: {{ .Values.deployment.container.containerPort | squote }}
            - name: BROKER_CLIENT_URL
              value: {{ .Values.brokerClientUrl }}
          {{- end }}
          {{- if eq .Values.scmType "bitbucket-server" }}
        # Bitbucket
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: BITBUCKET_USERNAME
              value: {{ .Values.bitbucketUsername }}
            - name: BITBUCKET_PASSWORD
              value: {{ .Values.bitBucketPassword }}
            - name: BITBUCKET
              value: {{ .Values.bitbucket }}
            - name: BITBUCKET_API
              value: {{ .Values.bitbucketApi }}              
            - name: PORT
              value: {{ .Values.deployment.container.containerPort | squote }}
            - name: BROKER_CLIENT_URL
              value: {{ .Values.brokerClientUrl }}
          {{- end }}
          {{- if eq .Values.scmType "gitlab" }}
         # Gitlab
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: GITLAB_TOKEN
              value: {{ .Values.scmToken }}
            - name: GITLAB
              value: {{ .Values.gitlab }}              
            - name: PORT
              value: {{ .Values.deployment.container.containerPort | squote }}
            - name: BROKER_CLIENT_URL
              value: {{ .Values.brokerClientUrl }}
          {{- end }}
          {{- if eq .Values.scmType "azure-repos" }}
          # Azure Repos
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: AZURE_REPOS_TOKEN
              value: {{ .Values.scmToken }}
            - name: AZURE_REPOS_ORG
              value: {{ .Values.azureReposOrg }}
            - name: AZURE_REPOS_HOST
              value: {{ .Values.azureReposHost }}        
            - name: PORT
              value: {{ .Values.deployment.container.containerPort | squote }}
            - name: BROKER_CLIENT_URL
              value: {{ .Values.brokerClientUrl }}
          {{- end }}
          {{- if eq .Values.scmType "artifactory" }}
          # Artifactory
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: ARTIFACTORY_URL
              value: {{ .Values.artifactoryUrl }}
          {{- end }}
          {{- if eq .Values.scmType "jira" }}
          # Jira
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: JIRA_USERNAME
              value: {{ .Values.jiraUsername }}
            - name: JIRA_PASSWORD
              value: {{ .Values.jiraPassword }}
            - name: JIRA_HOSTNAME
              value: {{ .Values.jiraHostname }}        
            - name: PORT
              value: {{ .Values.deployment.container.containerPort | squote }}
            - name: BROKER_CLIENT_URL
              value: {{ .Values.brokerClientUrl }}
          {{- end }}
          {{- if eq .Values.scmType "container-registry-agent" }}
          # Container Registry Agent
            - name: BROKER_TOKEN
              value: {{ .Values.brokerToken }}
            - name: CR_AGENT_URL
              value: http://127.0.0.1:{{ .Values.deployment.container.crSnykPort | toString }}
            - name: CR_CREDENTIALS
              value: {{ .Values.crCredentials }}       
            - name: PORT
              value: {{ .Values.deployment.container.containerPort | squote }}
            - name: BROKER_CLIENT_URL
              value: {{ .Values.brokerClientUrl }}
            - name: BROKER_CLIENT_VALIDATION_URL
              value: {{ .Values.crAgentUrl }}/systemcheck  
          {{- end }}
          #Logging
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: LOG_ENABLE_BODY
              value: {{ .Values.logEnableBody | squote }}
          #Troubleshooting
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: {{ .Values.tlsRejectUnauthorized }}
         {{- if .Values.caCert }}
            - name: CA_CERT
              value: {{ .Values.caCert }}
         {{- end }}
         {{- if .Values.httpsCert }}
            - name: HTTPS_CERT
              value: {{ .Values.httpsCert }}
         {{- end }}
         {{- if .Values.httpsKey }}
            - name: HTTPS_KEY
              value: {{ .Values.httpsKey }}
         {{- end }}
         {{- if .Values.accept }}
            - name: ACCEPT
              value: {{ .Values.accept }}
         {{- end }}
        {{- if eq .Values.scmType "container-registry-agent" }}
         # Container Registry Agent
        - name: {{ .Chart.Name }}-cr
          image: "{{ .Values.image.crRepository }}:{{ .Values.crImage}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SNYK_PORT
              value: {{ .Values.deployment.container.crSnykPort | squote }}    
        {{- end }}
